title: parasharvinay00.github.io # Title text on top of home page.
description: > # Description of the site for meta tags (SEO) (multiple lines allowed)
  Blog by Vinay Parashar. I write about my thoughts, learnings and experiences in the world of software development and technology.
